apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-snapshot-pvc
spec:
  storageClassName: csi-hostpath-sc
  dataSource:
    name: csi-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi