apiVersion: v1
kind: Pod
metadata:
  name: web-snapshot
  labels:
    app: web-snapshot
spec:
  containers:
    - name: kubernetes-intro
      image: andrey4281/kubernetes-intro:0.0.1
      readinessProbe:
        httpGet:
          path: /index.html
          port: 8000
      livenessProbe:
        tcpSocket: { port: 8000 }
      volumeMounts:
        - name: my-csi-volume
          mountPath: /app
  volumes:
    - name: my-csi-volume
      persistentVolumeClaim:
        claimName: storage-snapshot-pvc